/**
 * Created by ravimodha on 20/08/16.
 */

module.exports = function (sequelize, DataTypes) {
  var Restaurants = sequelize.define('Restaurants', {
      name:DataTypes.STRING,
      url_name:DataTypes.STRING,
      description:DataTypes.TEXT,
      website:DataTypes.STRING,
      wine_list_url:DataTypes.TEXT,
      ready_for_smart_distribution: DataTypes.INTEGER,
      uploaded_txt_file: DataTypes.INTEGER,
      num_of_lines: DataTypes.INTEGER,
      wine_list_format: {
          type: DataTypes.INTEGER,
          allowNull: true
      },
      impossible_to_process: DataTypes.INTEGER,
      no_wine_list_comment: DataTypes.TEXT,
      email:DataTypes.STRING(40),
      address:DataTypes.STRING,
      city_part:DataTypes.STRING,
      phone:DataTypes.STRING,
      phone_clean:DataTypes.STRING,
      fax:DataTypes.STRING,
      city:DataTypes.STRING,
      city_area:DataTypes.STRING(50),
      state_prov:DataTypes.STRING,
      zip:DataTypes.STRING,
      country:DataTypes.STRING,
      country_id:DataTypes.INTEGER,
      latitude:{
          type: DataTypes.STRING(12),
          allowNull: true
      },
      longitude:{
          type: DataTypes.STRING(12),
          allowNull: true
      },
      cuisine:DataTypes.STRING,
      tripadvisor_id:DataTypes.INTEGER,
      winespectator_id:DataTypes.INTEGER,
      opentable_id:DataTypes.INTEGER,
      zagat_id:DataTypes.INTEGER,
      allmenu_id:DataTypes.INTEGER,
      payment_accepted:DataTypes.STRING,
      minimum_for_delivery:DataTypes.STRING,
      average_entree:DataTypes.STRING,
      price:DataTypes.STRING,
      min_price: DataTypes.DECIMAL(10,2),
      max_price: DataTypes.DECIMAL(10,2),
      source: DataTypes.STRING(50),
      user_id:DataTypes.INTEGER,
      active:DataTypes.INTEGER,
      position:DataTypes.INTEGER,
      is_deleted:DataTypes.INTEGER,
      added_date: DataTypes.DATE,
      updated_date: DataTypes.DATE,
      add_customer_id:DataTypes.INTEGER,
      add_user_id:DataTypes.INTEGER,
      edit_customer_id:DataTypes.INTEGER,
      edit_user_id:DataTypes.INTEGER,
      average_rate: DataTypes.DECIMAL(10,2),
      is_there_menu:DataTypes.INTEGER,
      menu_num:DataTypes.INTEGER,
      wine_count:DataTypes.INTEGER,
      anticipated_completion: DataTypes.DATE,
      notifications_group:DataTypes.INTEGER,
      notifications_time:DataTypes.INTEGER,
      timeout_group:DataTypes.INTEGER,
      timeout_time:DataTypes.INTEGER,
      google_reference: DataTypes.STRING(500),
      google_address: DataTypes.STRING,
      google_phone: DataTypes.STRING,
      google_name: DataTypes.STRING,
      google_website: DataTypes.STRING,
      google_places_checked: DataTypes.INTEGER,
      reference_status: DataTypes.STRING(30),
      southernmac:DataTypes.INTEGER,
      city_old: DataTypes.STRING,
      state_prov_old: DataTypes.STRING,
      country_old: DataTypes.STRING,
      zip_old: DataTypes.STRING,
      latitude_old: DataTypes.STRING,
      longitude_old: DataTypes.STRING,
      phone_old: DataTypes.STRING,
      address_old: DataTypes.STRING,
      name_old: DataTypes.STRING,
      city_area_old: DataTypes.STRING,
      website_old: DataTypes.STRING,
      d_id: DataTypes.INTEGER,
      update2013: DataTypes.INTEGER,
      google_miss: DataTypes.STRING,
      date_added: DataTypes.DATE,
      google_id: DataTypes.STRING,
      rating: DataTypes.STRING(10),
      duplicated_2013: DataTypes.INTEGER,
      original: DataTypes.INTEGER,
      deduplication_2015: DataTypes.INTEGER,
      forDeletion: DataTypes.INTEGER,
      blacklist_check: DataTypes.INTEGER,
      deduplication_2015_original_id: {
          type: DataTypes.INTEGER,
          allowNull: true
      },
      no_wine_list_reason_id: DataTypes.INTEGER,
      no_wine_list_comment_explanation: DataTypes.STRING(1000),
      ready_for_cleaning: DataTypes.INTEGER,
      is_cleaned: DataTypes.INTEGER,
      wine_count_test: DataTypes.INTEGER,
      noti_delay_group_id:DataTypes.INTEGER
  },{
      tableName: "restaurants"
  });

  return Restaurants;
};